// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnbtnzvbddwvfvwqahjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuYnRuenZiZGR3dmZ2d3FhaGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzYzMDAsImV4cCI6MjA2ODI1MjMwMH0.56-SoSr08CZGWVHp7kjj5bjP2AHstQ3OOe1h3JZ0ZzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});